theme: jekyll-theme-cayman
auto_ids: true

# List of Zowe releases - update here and it will update the entire site :-)
# Note - keep this in order as the latest release is pulled from the first item in the list!
releases:
  - version: 1.4.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-4-0-august-2019
    release_date: 2019-08-09
    binary_download: https://projectgiza.org/Downloads/legal.1.4.0.html
    documentation: https://zowe.github.io/docs-site/latest/
  - version: 1.3.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-3-0-june-2019
    release_date: 2019-06-13
    binary_download: https://projectgiza.org/Downloads/legal.1.3.0.html
    documentation: https://zowe.github.io/docs-site/v1-3-x/
  - version: 1.2.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-2-0-may-2019
    release_date: 2019-05-03
    binary_download: https://projectgiza.org/Downloads/legal.1.2.0.html
    documentation: https://zowe.github.io/docs-site/v1-2-x/
  - version: 1.1.0
    release_notes: hhttps://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-1-0-april-2019
    release_date: 2019-04-03
    binary_download: https://projectgiza.org/Downloads/legal.1.1.0.html
    documentation: https://zowe.github.io/docs-site/v1-1-x/
  - version: 1.0.1
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-0-1-march-2019
    release_date: 2019-03-07
    binary_download: https://projectgiza.org/Downloads/legal.1.0.1.html
    documentation: https://zowe.github.io/docs-site/v1-0-x/
  - version: 1.0.0
    release_notes: https://zowe.github.io/docs-site/latest/getting-started/summaryofchanges.html#version-1-0-0-february-2019
    release_date: 2019-02-08
    binary_download: https://projectgiza.org/Downloads/legal.1.0.0.html
    documentation: https://zowe.github.io/docs-site/v1-0-x/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
